version: '3.8'
services:
  #  ฐานข้อมูล
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"  # เปลี่ยนจาก "5432:5432" เป็น "5433:5432" หรือพอร์ตอื่นๆ ที่ไม่ถูกใช้งาน
    volumes:
      - postgres-data:/var/lib/postgresql/data
  # จัดการฐานข้อมูล
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres-data:
